#SPDX-License-Identifier: MIT-0
---
# tasks file for aks

- name: Login en ACR usando podman_login
  containers.podman.podman_login:
    username: 00000000-0000-0000-0000-000000000000
    password: "{{ acr_access_token }}"
    registry: "{{ acr_login_server }}"
    
- name: Construir imagen frontend
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ frontend_image_name }}"
    tag: "{{ new_tag }}"
    path: "roles/aks/files/frontend"
    push: true
    state: build
    build:
      nocache: true

- name: Construir imagen backend
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ backend_image_name }}"
    tag: "{{ new_tag }}"
    path: "roles/aks/files/backend"
    push: true
    state: build
    
- name: Obtener credenciales de AKS
  ansible.builtin.command: az aks get-credentials --resource-group {{ resource_group }} --name {{ cluster_name }} --overwrite-existing
  changed_when: false
  
- name: Desplegar frontend
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ frontend_image_name }}"
        namespace: "default"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ frontend_image_name }}"
        template:
          metadata:
            labels:
              app: "{{ frontend_image_name }}"
          spec:
            nodeSelector: 
              kubernetes.io/os: linux
            containers:
              - name: "{{ frontend_image_name }}"
                image: "{{ acr_login_server }}/{{ frontend_image_name }}:{{ new_tag }}"
                ports:
                  - containerPort: 80
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "250m"
                    memory: "256Mi"
                    
- name: Exponer frontend con Load Balancer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ frontend_image_name }}-service"
        namespace: "default"
      spec:
        type: ClusterIP
        selector:
          app: "{{ frontend_image_name }}"
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80

- name: Desplegar el backend en el clúster de AKS
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ backend_image_name }}"
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ backend_image_name }}"
        template:
          metadata:
            labels:
              app: "{{ backend_image_name }}"
          spec:
            containers:
            - name: "{{ backend_image_name }}"
              image: "{{ acr_login_server }}/{{ backend_image_name }}:{{ new_tag }}"
              ports:
              - containerPort: 5000
              imagePullPolicy: Always

- name: Exponer backend para comunicación con frontend
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: backend-service
        namespace: default
      spec:
        selector:
          app: "{{ backend_image_name }}"
        ports:
          - protocol: TCP
            port: 80       
            targetPort: 5000 
        type: ClusterIP  

- name: Crear ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: contador-ingress
        namespace: default
      spec:
        ingressClassName: nginx
        rules:
        - http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "{{ frontend_image_name }}-service"
                  port:
                    number: 80
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: "{{ backend_image_name }}-service"
                  port:
                    number: 80
